# Copyright (C) 2018-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j2y18lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j2y18lte/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/samsung/j2y18lte/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/samsung/j2y18lte/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
    vendor/samsung/j2y18lte/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/samsung/j2y18lte/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/j2y18lte/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/samsung/j2y18lte/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/samsung/j2y18lte/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/j2y18lte/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/j2y18lte/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/j2y18lte/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/j2y18lte/proprietary/bin/tftp_server:system/bin/tftp_server \
    vendor/samsung/j2y18lte/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/samsung/j2y18lte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/j2y18lte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/j2y18lte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/j2y18lte/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/j2y18lte/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/j2y18lte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/j2y18lte/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/j2y18lte/proprietary/lib/libpdmapper.so:system/lib/libpdmapper.so \
    vendor/samsung/j2y18lte/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/j2y18lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libDiagService.so:system/vendor/lib/libDiagService.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so \
    vendor/samsung/j2y18lte/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so
